# Lists
## Struktur data List

In [21]:
aList = ["pram",33,"toronto",True]

In [14]:
print(aList)

['pram', 33, 'toronto', True]


List indexing

In [1]:
bin_colors=['merah','hijau','biru','kuning']

In [2]:
bin_colors[1]

'hijau'

List slicing

In [22]:
bin_colors=['merah','hijau','biru','kuning']

In [24]:
bin_colors[0:2]

['merah', 'hijau']

Iteration

In [26]:
bin_colors=['merah','hijau','biru','kuning']

In [29]:
for aColor in bin_colors:
    print(aColor+ "ken")

merahken
hijauken
biruken
kuningken


# Tuples
## Struktur data Tuples

In [15]:
bin_colors=('merah','hijau','biru','kuning')

In [18]:
bin_colors[3]

'kuning'

In [20]:
bin_colors[0]

'merah'

# Dictionary
## struktur data Dictionary

In [31]:
bin_colors={
    "manual_color":"kuning",
    "approved_color":"hijau",
    "refused_color":"merah"}

In [32]:
print(bin_colors)

{'manual_color': 'kuning', 'approved_color': 'hijau', 'refused_color': 'merah'}


In [40]:
bin_colors.get('approved_color')

'ungu'

In [37]:
bin_colors['manual_color']

'kuning'

In [38]:
bin_colors['approved_color']="ungu"

In [39]:
 print(bin_colors)

{'manual_color': 'kuning', 'approved_color': 'ungu', 'refused_color': 'merah'}


# Sets
## Struktur data Sets

In [42]:
hijau = {'grass', 'leaves'}

In [43]:
print(hijau)

{'leaves', 'grass'}


In [ ]:
hijau={'grass', 'leaves','leaves'}

In [44]:
print(hijau)

{'leaves', 'grass'}


In [52]:
merah = {'dandelions','leaves','fire hydrant'}

In [53]:
hijau = {'rose','blood','leaves','fire hydrant'}

In [55]:
hijau|merah

{'blood', 'dandelions', 'fire hydrant', 'leaves', 'rose'}

In [56]:
merah&hijau

{'fire hydrant', 'leaves'}

# DataFrames
## Strukur data DataFrames

In [57]:
 import pandas as pd

In [58]:
 df = pd.DataFrame([
... ['1', 'aldian', 22, True],
... ['2', 'parmudya', 23, False],
... ['3', 'kenaroh', 20, True]])

In [62]:
df.columns = ['id', 'nama', 'umur', 'decision']

In [63]:
df

id      nama  umur  decision
0  1    aldian    32      True
1  2  parmudya    23     False
2  3   kenaroh    40      True

Colum selection

In [64]:
df[['nama','umur']]

nama  umur
0    aldian    32
1  parmudya    23
2   kenaroh    40

In [65]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

row selection

In [66]:
 df.iloc[1:3,:]

id      nama  umur  decision
1  2  parmudya    23     False
2  3   kenaroh    40      True

In [73]:
 df[df.umur>25]



id     nama  umur  decision
0  1   aldian    32      True
2  3  kenaroh    40      True

In [74]:
df[(df.umur<35)&(df.decision==True)]

id    nama  umur  decision
0  1  aldian    32      True

# Matrix
## Sturktur data Matrix

In [7]:
import numpy as np

In [8]:
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32,
33]])

In [9]:
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [11]:
 print(type(myMatrix))


<class 'numpy.ndarray'>


# Abstrak
## tipe data abstrak : Vector

In [12]:
 myVector = [22,33,44,55]

In [13]:
 print(myVector)

[22, 33, 44, 55]


In [15]:
print(type(myVector))

<class 'list'>


In [16]:
 myVector = np.array([22,33,44,55])

In [17]:
 print(myVector)

[22 33 44 55]


In [18]:
print(type(myVector))

<class 'numpy.ndarray'>


# abstrak
## tipe data abstrak : Stack

In [80]:
class Stack:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def push(self, item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.items[len(self.items)-1]
    def size(self):
        return len(self.items)

In [82]:
stack=Stack()
stack.push('Red')
stack.push('Green')
stack.push('Blue')
stack.push('Yellow')

In [83]:
stack.pop()

'Yellow'

In [84]:
stack.isEmpty()

False

In [85]:
colors = ['Red']

In [86]:
colors.append('Green')
colors.append('Yellow')
colors.append('Blue')

In [87]:
colors

['Red', 'Green', 'Yellow', 'Blue']

# abstrak
## tipe data abstrak : Queue

In [72]:
class Queue:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def enqueue(self, item):
        self.items.insert(0,item)
    def dequeue(self):
        return self.items.pop()
    def size(self):
        return len(self.items)

In [73]:
queue = Queue()

In [74]:
queue.enqueue("Red")

In [75]:
queue.enqueue('Green')

In [76]:
queue.enqueue('Blue')

In [77]:
queue.enqueue('Yellow')

In [78]:
print(f"Size of queue is {queue.size()}")

Size of queue is 4


In [79]:
print(queue.dequeue())

Red
